### ISSUE TITLE
`hz.currentUser().fetch()` doesn't call `connect`

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/horizon#633] opened 2016-07-06 23:50 UTC
If you follow the instructions at https://horizon.io/api/horizon/#currentuser :

```
const hz = new Horizon();
hz.currentUser().fetch().subscribe( (user) => console.log(JSON.stringify(user)) );
```

It doesn't work, but if you call `connect` first it does.

**Comment by danielmewes** [comment] 2016-07-07 00:26
I think this is a duplicate of https://github.com/rethinkdb/horizon/issues/567

**Closed as completed by danielmewes** 2016-07-07 00:26 UTC
