### ISSUE TITLE
order() not working with watch()

### ISSUE THREAD

**Issue by lirbank** [rethinkdb/horizon#780] opened 2016-08-24 02:03 UTC
Server version: 2.0.0-beta-7
Client version: 2.0.0-beta-7

When using sort() with watch() the results come back in arbitrary order:

``` js
transactions.store({
  createdAt: new Date(),
  //createdAt: new Date().toString(),
  //createdAt: Math.random(),
});

transactions.order('createdAt').watch().subscribe(
  docs => {
    docs.map(e => e.createdAt).forEach(e => console.log(e));
  },
  error => console.log(error)
);
```

**Comment by deontologician** [comment] 2016-08-24 02:24
Ah yes, we meant to disallow this. Going to close as a dupe of #542

**Comment by lirbank** [comment] 2016-08-24 20:50
Ahh, got it. What about just a quick update to the docs (limit is required for order+watch)?

**Comment by deontologician** [comment] 2016-08-24 22:03
Actually, I have a fix I'll just do

**Closed as completed** 2016-08-24 22:03 UTC
