### ISSUE TITLE
Is there a way to auto create the database when you use hz set-schema?

### ISSUE THREAD

**Issue by datpham23** [rethinkdb/horizon#449] opened 2016-05-19 22:24 UTC
hz set-schema --project-name horizon-poc --start-rethinkdb no --config=./.hz/config.toml ./horizonSchema.toml

set-schema failed with ReqlQueryLogicError: Database name `horizon-poc` invalid (Use A-Za-z0-9_ only) in:
r(["horizon-poc", "horizon-poc_internal"]).forEach(function(var_0) { return r.branch(r.dbList().contains(var_0), [], r.dbCreate(var_0)); }).do(function() { return r(["collections", "users_auth", "users", "groups"]).forEach(function(var_1) { return r.branch(r.db("horizon-poc_internal").tableList().contains(var_1), [], r.db("horizon-poc_internal").tableCreate(var_1)); }); })

**Comment by danielmewes** [comment] 2016-05-19 23:01
`hz set-schema` always creates the database if it doesn't exist. The issue is that we don't support dashes in project names ( / database names) right now, so the database creation fails.

This is related to https://github.com/rethinkdb/horizon/issues/376 and we need to improve the handling of this, probably by escaping the project names and also by printing a better error message if there are other unsupported characters in it.

Try `--project-name horizon_poc`.

Going to close this as a duplicate of #376.

**Closed as completed by danielmewes** 2016-05-19 23:01 UTC
