### ISSUE TITLE
[2.0b7] Aut0 - authenticate on localhost fails due redirect_uri always is https

### ISSUE THREAD

**Issue by mcbain** [rethinkdb/horizon#791] opened 2016-08-25 15:50 UTC
The redirect always contains https protocol - local testing impossible. 
The request-protocol or the secure setting from config should be considered to be used.

utils.js 

``` code

[109] const self_url = (host, path) =>
    url.format({ protocol: 'https', host: host, pathname: path });

[120] const return_url = self_url(req.headers.host, request_url.pathname);
```

**Comment by danielmewes** [comment] 2016-08-25 19:46
Thanks for opening an issue for this @mcbain . This is actually a duplicate of https://github.com/rethinkdb/horizon/issues/508 .

**Closed as completed by danielmewes** 2016-08-25 19:46 UTC
