### ISSUE TITLE
Websocket error after upgrading to 1.0

### ISSUE THREAD

**Issue by ingro** [rethinkdb/horizon#392] opened 2016-05-17 15:43 UTC
Hello! Today I updated horizon to 1.0 and the client could not connect anymore to the server via websocket.

Running horizon with `hz serve --dev` the only response that I'm getting from the websocket is this:

```
{
  code: 1,
  message: "Session ID unknown"
}
```

Then I tried to run the server with the `--debug` flag, and that's the output:

```
debug: Handling HTTP request to horizon subpath: horizon.js
debug: Client connection established.
debug: Closing client connection with message: No connection to the database.
debug: info: {"error":"No connection to the database."}
debug: Client connection terminated.
debug: Handling HTTP request to horizon subpath: horizon.js.map
```

I also tried to create a new app with `hz init` but without luck.

As I said I'm running horizon 1.0 on node 5.10, the OS is Windows 7 x64.

**Comment by andrewsomething** [comment] 2016-05-17 16:44
I've seen this on Ubuntu 14.04 as well. Same error on the command line. Web console shows:

```
polling-xhr.js:250POST http://xxx.xxx.xxx.xxx:8181/horizon/?EIO=3&transport=polling&t=LI_bg_x&sid=VPQUJtIRdM_rxzfAAAAA 400 (Bad Request)o.create @ polling-xhr.js:250o @ polling-xhr.js:163u.request @ polling-xhr.js:91u.doWrite @ polling-xhr.js:104(anonymous function) @ polling.js:208(anonymous function) @ browser.js:325u @ index.js:23(anonymous function) @ browser.js:340(anonymous function) @ browser.js:320e.encodePacket @ browser.js:119o @ browser.js:319o @ browser.js:338s @ browser.js:345e.encodePayload @ browser.js:324n.write @ polling.js:207n.send @ transport.js:108n.flush @ socket.js:550n.sendPacket @ socket.js:610n.write.n.send @ socket.js:570c @ socket.js:63next @ socket.js:143e._next @ Subject.js:117e.next @ Subject.js:77e.__tryOrUnsub @ Subscriber.js:225e.next @ Subscriber.js:174e._next @ Subscriber.js:124e.next @ Subscriber.js:88e.notifyNext @ OuterSubscriber.js:19e._next @ InnerSubscriber.js:23e.next @ Subscriber.js:88e._finalNext @ Subject.js:128e._next @ Subject.js:120e.next @ Subject.js:77(anonymous function) @ socket.js:231t.subscribe @ Observable.js:52(anonymous function) @ socket.js:107r.emit @ index.js:134n.onOpen @ socket.js:396n.onHandshake @ socket.js:464n.onPacket @ socket.js:426(anonymous function) @ socket.js:258r.emit @ index.js:134n.onPacket @ transport.js:143r @ polling.js:145(anonymous function) @ browser.js:592e.decodePayloadAsBinary @ browser.js:591e.decodePayload @ browser.js:359n.onData @ polling.js:149(anonymous function) @ polling-xhr.js:124r.emit @ index.js:134o.onData @ polling-xhr.js:285o.onLoad @ polling-xhr.js:366hasXDR.r.onreadystatechange @ polling-xhr.js:238
index.js:66Received an error: Error: Websocket ws://xxx.xxx.xxx.xxx:8181 experienced an errort @ index.js:66e.__tryOrUnsub @ Subscriber.js:225e.error @ Subscriber.js:186e._error @ Subscriber.js:127e.error @ Subscriber.js:101e._error @ ConnectableObservable.js:115e.error @ Subscriber.js:101e._finalError @ Subject.js:149e._error @ Subject.js:136e.error @ Subject.js:97e.__tryOrUnsub @ Subscriber.js:225e.error @ Subscriber.js:186e._error @ Subscriber.js:127e.error @ Subscriber.js:101(anonymous function) @ socket.js:82r.emit @ index.js:134n.onError @ socket.js:670(anonymous function) @ socket.js:261r.emit @ index.js:134n.onError @ transport.js:65(anonymous function) @ polling-xhr.js:108r.emit @ index.js:134o.onError @ polling-xhr.js:296(anonymous function) @ polling-xhr.js:243
websocket.js:237WebSocket connection to 'ws://xxx.xxx.xxx.xxx:8181/horizon/?EIO=3&transport=websocket&sid=VPQUJtIRdM_rxzfAAAAA' failed: WebSocket is closed before the connection is established.
polling-xhr.js:250GET http://xxx.xxx.xxx.xxx:8181/horizon/?EIO=3&transport=polling&t=LI_bg__&sid=VPQUJtIRdM_rxzfAAAAA 400 (Bad Request)o.create @ polling-xhr.js:250o @ polling-xhr.js:163u.request @ polling-xhr.js:91u.doPoll @ polling-xhr.js:121n.poll @ polling.js:119n.onData @ polling.js:158(anonymous function) @ polling-xhr.js:124r.emit @ index.js:134o.onData @ polling-xhr.js:285o.onLoad @ polling-xhr.js:366hasXDR.r.onreadystatechange @ polling-xhr.js:238
polling-xhr.js:250POST http://xxx.xxx.xxx.xxx:8181/horizon/?EIO=3&transport=polling&t=LI_bh14&sid=VPQUJtIRdM_rxzfAAAAA 400 (Bad Request)
```

**Comment by danielmewes** [comment] 2016-05-17 17:09
I wonder if there is an issue with the Horizon metadata in RethinkDB.

The "No connection to the database" message indicates that there's either actually no connection to RethinkDB, or that the metadata couldn't get initialized correctly.

Do you have any important data stored in your Horizon application?
Otherwise, can you try shutting down Horizon, deleting the directory `rethinkdb_data` in your Horizon app directory, and then starting Horizon again in `--dev` mode? (this will delete any data stored for the application!)

On Windows, it might also be necessary to start a RethinkDB server manually, and to pass `--start-rethinkdb no -c localhost` to `hz serve`.

Let me know if that changes anything or if the issue is still there after these steps.

**Comment by danielmewes** [comment] 2016-05-17 17:31
@ingro @andrewsomething Could you also put the full output of `hz serve --dev --debug` into a Gist (gist.github.com , or similar) and share it here? That might provide some hints as to what's going on.

**Comment by andrewsomething** [comment] 2016-05-17 17:45
This is on a fresh sample app created with `hz init` I was able to start it once successfully. After killing it and starting it again, I'm seeing the issue again:

https://gist.github.com/andrewsomething/3b3a237d9b2d1d64f234ddab6b5f7e7e

**Comment by danielmewes** [comment] 2016-05-17 17:53
Thanks for sharing the logs @andrewsomething .

I can actually reproduce it now. Looking into it.

**Comment by benjick** [comment] 2016-05-17 17:58
Just downloaded 1.0.0, never tried horizon before, seeing these errors: https://gist.github.com/benjick/cf3e7960ba3df1fe350d17368de5f5b5

I can access the admin panel

OSX 10.11.4, Node 6.1.0

Edit: sorry, didn't see your comment before I started writing mine @danielmewes

**Comment by ingro** [comment] 2016-05-17 18:22
@danielmewes same behaviour as reported by @andrewsomething, the issue appear after the first successfull start.

**Comment by danielmewes** [comment] 2016-05-17 18:39
We have a fix, will be releasing 1.0.1 soon.
Sorry for the bug everybody!

**Comment by danielmewes** [comment] 2016-05-17 18:41
A work-around is to start your own RethinkDB server by the way and then using the `--start-rethinkdb no -c localhost` flags with `--dev`.

**Comment by danielmewes** [comment] 2016-05-17 18:49
Fixed via https://github.com/rethinkdb/horizon/pull/397

**Closed as completed** 2016-05-17 18:50 UTC
Labels: bug

**Comment by danielmewes** [comment] 2016-05-17 18:59
Shipping with Horizon 1.0.1 which is being published to NPM in this minute.

**Comment by dalanmiller** [comment] 2016-05-17 19:04
horizon 1.0.1 is now published to npm

https://www.npmjs.com/packages/horizon

**Comment by andrewsomething** [comment] 2016-05-17 19:25
Confirming that I can no longer reproduce the issue. Thanks for the quick fix! :clap:

**Comment by ingro** [comment] 2016-05-17 20:23
Thanks for the fast fix :)

**Comment by steelbrain** [comment] 2016-05-18 02:31
I am still able to repro this on the Horizon v1.0.1
This is the relevant info from `hz ... --debug`

```
Horizon ready for connections 🌄
debug: Handling HTTP request to horizon subpath: horizon.js
debug: Client connection established.
debug: Received handshake: {"method":"unauthenticated","request_id":3}
debug: Closing client connection with message: Error: Unauthenticated connections are not allowed.
debug: info: {"request_id":3,"error":"Error: Unauthenticated connections are not allowed.","error_code":0}
debug: Client connection terminated.
```

The CLI params are

```
hz serve --secure no --auto-create-collection --auto-create-index --allow-anonymous --connect localhost:28015
```

**Comment by danielmewes** [comment] 2016-05-18 03:02
@steelbrain That's different.
You can either start with `--allow-unauthenticated`, or use `var horizon = Horizon({authType: "anonymous"});` in your application. See http://horizon.io/docs/auth/ for the difference between unauthenticated and anonymous.

**Comment by steelbrain** [comment] 2016-05-18 07:34
@danielmewes The way authentication is handled has changed a lot. I am able to connect to rethinkdb but everything returns `Operation not permitted`, perhaps this issue is not the right place to discuss it. But is there any upgrade guide for beta users?

**Comment by danielmewes** [comment] 2016-05-18 07:59
@steelbrain The `Operation not permitted` result indicates that the query was not permitted by the Horizon permission system. Since there was no permission system in the beta, it makes sense that the update broke your setup in this respect.

You can read how the permissions system works and how you can configure it in http://horizon.io/docs/permissions

If you don't need to restrict data access and/or writes, you can also disable the permissions system by starting `hz serve` with the `--permissions no` option, or by putting the equivalent option (`permissions = false`) into the `.hz/config.toml` file of your project.

Unfortunately we haven't written a beta migration guide so far.
