### ISSUE TITLE
Horizon token is left in the URL after OAuth

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/horizon#625] opened 2016-06-30 23:57 UTC
If I go to `dev.hzc-dev.io:8181` and authenticate with GitHub, at the end of the chain I end up at `dev.hzc-dev.io:8181/?horizon_token=BUNCH.OF.STUFF` rather than back at the page I started at.  I think after we read the token out of the URL we should remove it.

**Comment by deontologician** [comment] 2016-07-07 22:35
Duplicate of #492

**Closed as completed** 2016-07-08 00:14 UTC
