### ISSUE TITLE
Horizon ignores the `host` it was passed when fetching `auth_methods`

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/horizon#640] opened 2016-07-15 00:21 UTC
If I write `hz = Horizon({host: SOME_HOST})`, it still tries to read `localhost:8080/horizon/auth_methods` instead of `host/horizon/auth_methods`.

**Comment by mlucy** [comment] 2016-07-15 00:21
(This was in 1.1.3.)

**Comment by deontologician** [comment] 2016-07-15 01:23
This is a dupe of #422 which is slated for 2.0 (I'm probably working on this next since #634 is about done) Also @mlucy would you like to review #634?

**Closed as completed by deontologician** 2016-07-15 01:23 UTC
Labels: bug
