### ISSUE TITLE
Error on connection to RethinkDB: Error: write EPIPE

### ISSUE THREAD

**Issue by Rajan** [rethinkdb/horizon#739] opened 2016-08-11 08:09 UTC
debug: Received request from client: {"type":"store","options":{"collection":"betausers","data":[{"datetime":{"$reql_type$":"TIME","epoch_time":1470902434.534,"timezone":"Z"},"email":"aa@aa.com"}]},"request_id":9}
debug: Received request from client: {"request_id":10,"type":"end_subscription"}
debug: Sending response: {"data":[{"id":"3667de9f-2190-4e41-8d97-98102a20a9db","$hz_v$":0}],"state":"complete","request_id":9}
debug: Received request from client: {"request_id":9,"type":"end_subscription"}
debug: Client connection terminated.
^Cerror: Error on connection to RethinkDB: Error: write EPIPE.

Server version: RethinkDB 2.3.1Web UI Settings
Client version: Horizon 2.0

**Comment by deontologician** [comment] 2016-08-15 21:31
Hi @Rajan does this happen every time? What were the conditions in place when this occurred?

**Comment by Tryneus** [comment] 2016-08-18 21:59
This appears to be during shutdown, notice the `^C` - the problem is likely that a connection to RethinkDB was still open when we kill the server, and so it gets an error when writing.  I revamped server shutdown in `v2.0.x`, so it's possible this is no longer a problem.

**Comment by deontologician** [comment] 2016-08-19 03:00
I'm going to close this for now since there's not enough to go on. @Rajan if you run into this again, or have time to provide more details we can reopen it

**Closed as completed by deontologician** 2016-08-19 03:00 UTC
