### ISSUE TITLE
Horizon can't connect if RethinkDB authentication is required

### ISSUE THREAD

**Issue by bweinand** [rethinkdb/horizon#573] opened 2016-06-08 14:08 UTC
I'm new to RethinkDB and Horizon, maybe I'm missing something.

The RethinkDB server and driver port require access from the outside world. So I have to use the RethinkDB authentication system and set the admin password. If the admin user has a password set, Horizon is not able to connect (--connect).

Is it possible to give Horizon a user and password for the connection to RethinkDB? Other solutions? (SSH tunnel to the driver port is NOT an option).

**Comment by alf** [comment] 2016-06-08 17:24
It's a work in progress #507

**Comment by bweinand** [comment] 2016-06-08 17:32
Perfect. Did not see that. Thank you.

**Comment by deontologician** [comment] 2016-06-09 16:51
Seems to be a duplicate of #288 (took me 10 minutes to find it!)

Thanks for opening this though @bweinand, we knew this needed to be done but it's always helpful to see people actually running into the issue

**Closed as completed by deontologician** 2016-06-09 16:51 UTC
