### ISSUE TITLE
Uncaught TypeError: (0 , b.default)(...).do is not a function

### ISSUE THREAD

**Issue by lyonzy** [rethinkdb/horizon#462] opened 2016-05-20 06:11 UTC
Hello,

I'm getting this when trying to to twitter authentication:

`horizon.js:formatted:2834 Uncaught TypeError: (0 , b.default)(...).do is not a function`

I believe this is when it's trying to fetch /horizon/auth_methods - this line:

auth.js line 16
`return fetchJSON('${this._horizonPath}/auth_methods')`

(I've changed some backticks to apostrophes to make it markdown-safe).

Any ideas why my fetchJSON hasn't got a `do` method?

Cheers,
Matt

**Comment by marshall007** [comment] 2016-05-20 06:32
I think this is a dupe of #446 which was fixed earlier today in #455.

**Comment by lyonzy** [comment] 2016-05-20 06:33
Yeah I just realised that myself. Cheers :)

**Closed as completed** 2016-05-20 08:02 UTC
